image: debian/stable
oauth: pages.sr.ht/PAGES:RW
packages:
- git
- ruby-full
- ruby-dev
- ruby-bundler
- sudo
- gcc
- make
- libsqlite3-dev
- sqlite3
environment:
secrets:
-  a9c8555e-d2d0-4a61-acf6-f869c25d668a
site: dsa-planet.srht.site
sources:
- https://git.sr.ht/~cmahns/dsa-planet.srht.site
tasks:
- install-bundler: |
    sudo gem install bundler -v 2.3.26
- build: |
    cd dsa-planet.srht.site 
    bundler install
    bundler exec rake build
    bundle exec jekyll build
- package: |
    cd dsa-planet.srht.site/_site
    tar -cvz . > ../../site.tar.gz
- upload: |
    curl --oauth2-bearer "
AC2wqGUAAAAAQHBhZ2VzLnNyLmh0L1BST0ZJTEU6UlcgcGFnZXMuc3IuaHQvU0lURVM6UlcgcGFnZXMuc3IuaHQvUEFHRVM6UlcABmNtYWhucw9m4z61vmo9savaMq3eoNEa/7NP2hnZBkhxbGwjFp9N
" \
    -Fcontent=@site.tar.gz \
    https://pages.sr.ht/publish/dsa-planet.srht.site
