require:
    - rubocop-rake

CyclomaticComplexity:
    Max: 15

PerceivedComplexity:
    Max: 15

Layout/LineLength:
    Max: 120

Metrics/MethodLength:
    Max: 20

    AllCops:
        TargetRubyVersion: 3.0
