name: Request Feed Inclusion

on:
    issues:
        types: [labeled]

permissions: read-all

env:
    CHAPTER_NAME: requested-addition

jobs:
    include-feed:
        if: ${{ contains(github.event.issue.labels.*.name, 'addition') }}
        runs-on: ubuntu-latest

        permissions:
            pull-requests: write
            contents: write
            actions: write

        steps:
            - uses: actions/checkout@v7

            - id: parse-issue
              uses: issue-ops/parser@v5
              with:
                  body: ${{ github.event.issue.body }}
                  issue-form-template: feed-request.yml

            - uses: ruby/setup-ruby@v1.316.0
              with:
                ruby-version: 4.0
                bundler-cache: true

            - run: bundler install

            - uses: mfinelli/setup-imagemagick@v8

            - id: add-feed-to-ini
              run: |
                escaped_json='${{ steps.parse-issue.outputs.json }}'
                bundle exec ruby tests/feed_request.rb "$escaped_json"

            - id: simple-chapter-name
              run: |
                raw_name='${{ fromJSON(steps.parse-issue.outputs.json).dsa-body }}'
                sanitized_name=$(echo $raw_name | tr '[:upper:]' '[:lower:]' | tr -dc '[:alnum:]\n\r' | tr ' ' '-')
                echo "CHAPTER_NAME=$sanitized_name" >> $GITHUB_ENV

            - run: bundle exec ruby tests/feedcheck.rb ${{ env.CHAPTER_NAME }}

            - if: failure()
              run: cat error-summary.md >> $GITHUB_STEP_SUMMARY

            - if: failure()
              run: gh issue comment "$NUMBER" --body "$BODY"
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GH_REPO: ${{ github.repository }}
                NUMBER: ${{ github.event.issue.number }}
                BODY: |
                  Unfortunately the feeds did not pass automated checks. Please verify the submitted information.

            - if: success()
              uses: peter-evans/create-pull-request@v8
              with:
                  branch: "add-${{ env.CHAPTER_NAME }}"
                  title: "Add Feed for ${{ fromJSON(steps.parse-issue.outputs.json).enter_your_chapter_or_working_group_name }}"
                  body: |
                    DSA Body: ${{ fromJSON(steps.parse-issue.outputs.json).enter_your_chapter_or_working_group_name }}
                    Feed URL: ${{ fromJSON(steps.parse-issue.outputs.json).what_is_your_rss_feed }}
                    Site URL: ${{ fromJSON(steps.parse-issue.outputs.json).what_is_your_website }}
                    Image URL: ${{ fromJSON(steps.parse-issue.outputs.json).what_image_do_you_want_to_use }}
                  commit-message: |
                    add ${{ fromJSON(steps.parse-issue.outputs.json).enter_your_chapter_or_working_group_name }} feed to planet.ini.
                    closes issue #${{ github.event.issue.number }}
