name: Jekyll CI

'on':
  push:
    paths-ignore:
      - '*.md'
      - 'tests/feedcheck*.rb'
      - .github/workflows/feeds.yml
      - .github/workflows/feed-request.yml
    branches:
      - master
  pull_request:
    paths-ignore:
      - '*.md'
      - 'tests/feedcheck*.rb'
      - .github/workflows/feeds.yml
      - .github/workflows/feed-request.yml
    branches:
      - master
  schedule:
    - cron: 0 8,12,16,20 * * *
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1.255.0
        with:
          ruby-version: 3.2.7
          bundler-cache: true

      - name: Install Dependencies
        run: bundler install

      - name: Configure Feed Cache
        uses: actions/cache@v4
        with:
          path: planet.db
          key: cache-feed-sources-${{ hashFiles('Gemfile.lock') }}-${{ hashFiles('planet.db') }}

      - name: Get and Proccess Feed Content
        run: bundler exec rake build

      - name: Build Jekyll Site
        run: bundler exec jekyll build

      - uses: actions/upload-pages-artifact@v3

  deploy:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: '${{ steps.deployment.outputs.page_url }}'
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
